### ISSUE TITLE
Make release

### ISSUE THREAD

**Issue by rodinaarssen** [usethesource/rascal-language-servers#107]
- [x] Adapt JVM auto downloader to accept Java 11
- [x] Resolve #88 
- [x] Write release notes
  - [x] Current version
  - [x] Previous versions?
- [x] Test functionality
  - [x] Rascal
  - [x] DSL
  - [x] Terminal links

**Comment by DavyLandman** [comment]
Agreed, also this time we shouldn't forget release notes (#92)

**Comment by jurgenvinju** [comment]
And required to do _before_ a Java11 branch merge.

For releasing rascal-eclipse we  have a rather specific protocol; in the absence of fool proof automated UI tests. Let's mimick this for the current project as well? We have an issue template for the release with check-boxes for every manual step. When I release rascal-eclipse, I register and new issue, pick the release template, and start going through the motions until everything is done. If the steps change due to evolving features of the project, I edit the template and commit it with the project. Makes sense? 

* See https://github.com/usethesource/rascal/issues/1416 for an example. 
* See https://github.com/usethesource/rascal/tree/master/.github/ISSUE_TEMPLATE for the templates

**Comment by DavyLandman** [comment]
agreed, but let's go for a lighter variant of that one for now.

And invest time into automated vscode tests. I think @rodinaarssen was reading up on that a bit already.

**Comment by jurgenvinju** [comment]
ok.

I am afraid of regressions regarding  the behavior of the terminal, calling the registerLanguage feature on the terminal, link resolution, and HTML server/client API that we do not use a lot yet. Complex stuff and worthy features, but hard to test automatically.

**Comment by rodinaarssen** [comment]
Done.

**Comment by DavyLandman** [comment]
🎉
