### ISSUE TITLE
Add VSCode's Virtual File Systems to URIResolverRegistry of Rascal

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/rascal-language-servers#128]
Currently the virtual filesystems of rascal are exposed to VSCode. To finish this integration we need to expose the virtual filesystems of vscode to rascal as well.

Since VSCode doesn't support listing it's registered scheme's, we'll have to forward any non-resolved URI to vscode, and see if it can resolve it for us.

Note that there is a proposal to add this to LSP somewhere in the future: https://github.com/microsoft/vscode-languageserver-node/pull/782 we could try to get our API close to that, to help the migration effort when it's available.

**Comment by jurgenvinju** [comment]
This entails a serious new feature for the URIResolverRegistry class in the usethesource/rascal project. Propose to create a new issue there which allows the registry to resolve schemes to one-or-more "external" registries if all else fails. 

Note that this requires some thinking. Not finding files is very common and we should not have to communicate over sockets to resolve simple `exists` queries for files that _are_ local. 

* Focusing on `schemes` only should alleviate the burden; 
* We should _never_ extend the mechanism to resolve either authorities or paths if they can't be found locally
* We could decide to implement the `+` scheme splitting locally, such that remote schemes can profit from this feature without extending VScode.

**Comment by DavyLandman** [comment]
Agreed, it should be on a scheme basis. however, if you have a local `project` resolver, you can have a fallback `project` external resolver as well.

**Comment by jurgenvinju** [comment]
I think that would be a mistake; both logically and in terms of efficiency. And why would we need that? 

The `project` scheme is supposed to come out of the IDE anyway, so it should be implemented via the non-local route as soon as we have that opportunity. In a way, the current implementation of `project` is a special case of what we are proposing anyway.

**Comment by DavyLandman** [comment]
okay, true, maybe project should not be a local thing.

**Comment by jurgenvinju** [comment]
The hard think will be to get all of this right while the JVM is starting and loading classes. The entire URIResolverRegistry and "builtin" schemes like `lib` are predicated on the fact that they load "statically" and on-demand. This new way of working has to integrate with that old way of working, yet still _wait_ for a working socket connection. The parameters of this socket connection are hopefully passed in via the `main` method, but still the URIResolverRegistry is a singleton class. IOW I foresee quite some re-engineering in the _rascal_ project with large possible impact.

**Comment by jurgenvinju** [comment]
In particular schemes that depend on each-other are "interesting"; currently they are allowed to cache resolution at class loading time, while in the new scheme (if external schemes can come into play) such caching would break the abstraction. 

For example: `lib://<project>` tests if `plugin://<project>` exists at class loading time now and caches the result, because it assumes that `plugin` is implemented by the class loading mechanism of the current IDE context. This works for Eclipse, but not for VScode where `plugin` is (will be) implemented by the external mechanism. At class loading time for URIResolverRegistry and the LibraryResolver the `plugin` scheme will not be available yet because the socket hasn't connected. etc.

**Comment by DavyLandman** [comment]
Closing this, this was implemented in #158
