### ISSUE TITLE
Release rascal-lsp & vscode-lsp wrapper as a seperate dependency on npm (for deploying rascal DSLs without dependencies on rascal-vscode extension)

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/rascal-language-servers#189]
**Is your feature request related to a problem? Please describe.**
Currently, if we deploy a VS Code DSL that uses Rascal, we have to make a extension that depends on the rascal vscode extension. But you'll always get updated to the latest version. So 2 years in the future, that DSL extension might break due to a breaking change that happened in the rascal-vscode extension.

**Describe the solution you'd like**
I think properly restricting the project to full backwards compatiblity is not feasible or even wise at this moment. So I want to propose we bundle up the language parametric "side" of rascal-lsp & rascal-vscode-extension in a npm package. This npm package contains everything you need to run a Rascal DSL from outside a rascal repl. So we can deploy a new extension, that has a fixed dependency on this npm package, it starts it's own LSP process and is not depending on any specifics of the rascal vscode extension that is or is not installed.

This would even allow multiple DSL installed, with different versions of rascal & rascal-lsp.

The only problem I forsee is with the VFS, the first rascal jar that is started would win that race. So we have to be very careful to remain backwards compatible there, or think of some complicated redesign of that registry component.

**Describe alternatives you've considered**
Extend the rascal-lsp interface with a way to allow extensions to request older version of rascal & rascal-lsp. This seems like a fragile approach, where we would lock down this api for future changes, and would dynamically be downloading jars & javascript files and loading them, not sure if that would even work.

**Additional context**
This continues the idea presented in #94

**Comment by jurgenvinju** [comment]
* the VFS URI schemes are supposed to implement unique identification mechanisms, and so it should not matter who resolves them. If we run into the problem that it matters which resolver does the work, then we have to re-think that scheme rather than this solution. It could be however that we need to _multiplex_ if some resolvers offer other schemes...

**Comment by jurgenvinju** [comment]
* Deployment on npm. Is that necessary/wanted? What are the pros and cons, and alternatives?

**Comment by DavyLandman** [comment]
> * the VFS URI schemes are supposed to implement unique identification mechanisms, and so it should not matter who resolves them. If we run into the problem that it matters which resolver does the work, then we have to re-think that scheme rather than this solution. It could be however that we need to _multiplex_ if some resolvers offer other schemes...

What if I have a DSL with rascal version X, and it's started first, so we get the VFS from version X.

Now the Rascal VS Code extension starts (or another DSL for that matter) with rascal version Y. And it expects newer VFS operations than we had in X?

> Deployment on npm. Is that necessary/wanted? What are the pros and cons, and alternatives?

If don't see a way around it, as the user extension will be a typescript package that gets compiled into vsix, so it's dependencies come from npm. We could do something where we download the jar dependency as during `npm install` instead of storing it along side, but apart from that, I don't think there is another way.

**Comment by jurgenvinju** [comment]
* What is a "VFS operation"? how can it be newer?
* Is there, like for maven, a way to host your own npm repository? and would that be a good thing or a bad thing?

**Comment by DavyLandman** [comment]
> * What is a "VFS operation"? how can it be newer?

If we add a new function to the VFS API.

>     * Is there, like for maven, a way to host your own npm repository? and would that be a good thing or a bad thing?

I think there might be a way, but it's very uncommon.

**Comment by jurgenvinju** [comment]
* ok, let's publish on npm then; at least we've stood still at alternatives :-)
* the VFS API is now a one-to-one reflection of the VFS API in VScode; so I would not expect we go fast there. Nevertheless, backward compatibility is very important in that API. We {c,sh,w}ould write tests for that to make sure we remember.

**Comment by jurgenvinju** [comment]
The other thing is the prevention of code duplication. It would be easy to clone the LSP and make one version that does not have the multiplexer and one that does. This would duplicate large parts of rascal-lsp, with the maintenance that comes with it. 

Since the rascal-lsp project is a rather complex piece of code (mainly due to asynchronous JSON-RPC handling), we talked about (other medium) factoring out a single Rascal-LSP Java interface for one language, which can either be plugged in a single host or can be plugged into the multiplexer. This way I hope we factor out most commonalities. 

I'm not sure, however. It seems there are also on the server/dispatch side where we plugin into lsp4j both the unit lsp server and the multiplexer would have to do similar things. 

There is a design possible where we:
* receiver/send information directly via LSP4J with one host, and do the asynchronous scheduling
* plug a handler (via dependency injection) that is a Java interface for Rascal-based LSP candidates
* implement two different implementations of the handler, one for multiplexed LSPs, and one for "normal" single LSPs

This way we separate the multiplexing strictly from asynchronous scheduling part, and we can reuse the latter in two situations. Thoughts?

**Comment by DavyLandman** [comment]
This sounds rather complex.

My goal would be to just have the option to run the `ParametricLanguageServer` outside of the rascal-vscode extension. That way all (/most) of the code remain the same, it's just that the multiplex is most likely less used.  Although we've certainly had multiple languages running side by side.

So an end-user plugin is not depending on any mechanism coming from the Rascal VS Code extension.

**Comment by jurgenvinju** [comment]
o right! that sounds like a simple plan. Just run the multiplexer with only one language in it. dûh! thanks Davy :-)
