### ISSUE TITLE
Rascal summary is dirty; most of the time

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#259]
**Describe the bug**

* change a module (in this case I'm editing in the standard library)
* save to get the new type and name errors
* try to use the summary by following a reference
* the reference only works if it already worked for the previous version of the file
* type a space somewhere and save again
* now the reference works

**Comment by DavyLandman** [comment]
The challenge is that the rascal typechecker is running against the files on disk, instead of taking a tree we pass in. Inside rascal-lsp we always connect stuff to the specific tree. But if that file gets updated during the runtime of the rascal type checker, we can loose track of which changes are propogated to the IDE version.

Especially with unsaved changes this gets very complex.

We might have to think hard about this logic, and just not return any data if we don't know exactly that the files are stable enough for us to provide the data.

**Comment by jurgenvinju** [comment]
ok thanks.

* this has nothing to do with unsaved changes; just to be clear. The analysis is always exactly one save step behind reality. 
* so please be open to the possibility that this is a simple bug.

**Comment by jurgenvinju** [comment]
* this could be a race between the messages we pass over the VFS bridge and the other LSP messages, for example.

**Comment by DavyLandman** [comment]
It's very unlikely to be the VFS, since it's over the file scheme in 99% or the cases (only remote ssh stuff you van trigger the rascal type checker over VFS).

I assume you made sure to wait for the type checker to finish running? If that's the fix we might have to think about an earlier point of invalidating cached summaries, although I thought we already do that quite eagerly.

Could you help construct a small demo project where this fails? As I've just tried to reproduce it (using your steps) and cannot observe this behavior.

I started out with:

```rascal
module A

import IO;

void main() {
    println("Hoi hoi");
}
```

and saved it (waiting for the check progress bar to finish), and verified I could jump to the definition of `println`.

Then I added a new line:

```rascal
module A

import IO;

void main() {
    println("Hoi hoi");
    println(uuencode(|tmp://test.txt|));
}
```

Saved it, and I could jump to the definition of `uuencode`. Could you do the same experiment?

**Comment by jurgenvinju** [comment]
This would also explain why we have seen fewer issues with simple DSL scenarios where module import plays less of a rule, and demos with Pico naturally do not have imports either.

**Comment by DavyLandman** [comment]
True, this could be related. And less present for simpeler dsls also since
their summaries are not polluted with info from other files? Or maybe the
are as well, but I think DSL side we have some similar filtering already
happening.

**Comment by jurgenvinju** [comment]
Right that makes a lot of sense. The summaries are already focused on one file for most DSL implementations.

**Comment by jurgenvinju** [comment]
I will test the solution of #260 to see if it also helps with this one.
