### ISSUE TITLE
[debugger] Value printer uses static type, not dynamic type

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/rascal-language-servers#295]
**Describe the bug**

The debugger uses the static type to display values, so if a function takes `value` as an argument, it will display it as a value, instead of as a set or a node for example. 

**To Reproduce**

```rascal
import IO;

void main() {
    value v = {1,2,3};
    v2 = {1,2,3};
    println(v);
}
```

set breakpoint on `println` line. See the locals difference between v and v2. v printed as a simple string, and the hover type is value. while v2 has the type `set[int]` and you can gradually dive into the values.

**Expected behavior**
Use dynamic type

**Screenshots**
![image](https://github.com/usethesource/rascal-language-servers/assets/179603/54a95aa0-5655-4d6b-b1e3-cfa8a2626fc3)

**Desktop (please complete the following information):**
 - Context: VS Code extension
 - Rascal Version: latest 0.9.1 release of vscode

**Comment by jurgenvinju** [comment]
let's switch altogether from static types to dynamic types in this view. For documentation  purposes we could use the static types as labels. To get a dynamic type from a value: `IValue.getType()` will produce the same information as `Result<?>.getType()` but it will be the dynamic type instead of the static type.
